version: '2'
services:
  actioncatalogservicesql-app:
    image: actioncatalogservicesql
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://actioncatalogservicesql-mongodb:27017/?waitQueueMultiple=1000
      - SPRING_DATA_MONGODB_DATABASE=ActionCatalogServiceSQL
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  actioncatalogservicesql-mongodb:
    extends:
      file: mongodb.yml
      service: actioncatalogservicesql-mongodb
